version: '3.8'

services:

  # Back-end container with Spring
  backend:
    image: trinhvideo123/langthang:latest
    container_name: langthang-backend
    restart: unless-stopped
    environment:
      HOST: http://localhost
    networks:
      langthang:
        aliases:
          - spring

  # Front-end container with Nginx
  frontend:
    image: trinhvideo123/langthang:frontend
    container_name: langthang-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      langthang:
        aliases:
          - frontend

networks:
  langthang: