spring:
  env: dev
  api-limit:
    enabled: true
  config:
    import: classpath:application-private.yml
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  datasource:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        search:
          default:
            directory_provider: filesystem
            indexBase: lucene_index
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Ho_Chi_Minh

cloud:
  aws:
    bucket:
      image-bucket: langthang-user-photos
      backup-bucket: lang-thang-backup
      cloud-front: https://cdn.langthang.tech
    region:
      static: ap-southeast-1
    public:
      base-url: ${cloud.aws.bucket.cloud-front}

application:
  image:
    support-type: image/png,image/jpg,image/jpeg
    pattern: ${cloud.aws.public.base-url}/\S*?.(jpg|png|jpeg)
  broker:
    prefix: /topic
    end-point: /socket-server
    notify:
      prefix: ${application.broker.prefix}/notify
    post:
      prefix: ${application.broker.prefix}/post
  notify-template:
    like-comment: "<b>{0}</b> đã thích bình luận của bạn trong bài viết <b>{1}</b>"
    comment-post: "<b>{0}</b> đã bình luận về bài viết <b>{1}</b>"
    bookmark-post: "<b>{0}</b> đã bookmark bài viết <b>{1}</b>"
    following-new-post: "<b>{0}</b> đã đăng một bài viết mới <b>{1}</b>"
  server:
    url: ${HOST:https://langthang.tech}

server:
  compression:
    enabled: true
  port: ${PORT:8080}
  http2:
    enabled: true

logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      langthang: DEBUG