spring:
  env: ${ENV:DEV}
  api-limit:
    enabled: false
  cache:
    enabled: false
  config:
    import: classpath:application-private.yml
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100

    open-in-view: false
    database-platform: POSTGRES
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  jackson:
    date-format: yyyy/MM/dd HH:mm

cloud:
  aws:
    bucket:
      image-bucket: langthang-user-photos
      backup-bucket: lang-thang-backup
      cloud-front: https://cdn.langthang.tech
    region:
      static: ap-southeast-1
    public:
      base-url: ${cloud.aws.bucket.cloud-front}

application:
  image:
    support-type: image/png,image/jpg,image/jpeg
    pattern: ${cloud.aws.public.base-url}/\S*?.(jpg|png|jpeg)
  broker:
    prefix: /topic
    end-point: /socket-server
    notify:
      prefix: ${application.broker.prefix}/notify
    post:
      prefix: ${application.broker.prefix}/post
  notify-template:
    like-comment: "<b>{0}</b> đã thích bình luận của bạn trong bài viết <b>{1}</b>"
    comment-post: "<b>{0}</b> đã bình luận về bài viết <b>{1}</b>"
    bookmark-post: "<b>{0}</b> đã bookmark bài viết <b>{1}</b>"
    following-new-post: "<b>{0}</b> đã đăng một bài viết mới <b>{1}</b>"
  server:
    url: ${HOST:https://langthang.tech}

server:
  compression:
    enabled: true
  port: ${PORT:8080}

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        stat: DEBUG
        SQL_SLOW: INFO
    com:
      langthang: DEBUG
